extends: ../../../ChineseEEG2_LittlePrince_sub01_sub02_actual_reading_1s_cnn_only.yaml

experiment:
  task: word_decoding
  dataset: chineseeeg2_littleprince
  subject_scope: sub01-02
  id: scaling_word
  category: scaling
