extends: ../base.yaml

experiment:
  task: word_decoding
  dataset: smn4lang
  subject_scope: sub01-06
  id: main_word
  category: main

model:
  use_transformer: false

provenance:
  context_condition: conv_only
