extends: ../../../SMN4Lang_1s_cnn_warm_start.yaml

experiment:
  task: word_decoding
  dataset: smn4lang
  subject_scope: sub01
  id: ablation_context_warm_start
  category: ablation

training:
  warm_start_from: dev_word
