extends: LibriBrain100_1s.yaml

model:
  context_mode: singleton

training:
  output_dir: outputs/LibriBrain100/word_decoding_1s_single_word_transformer

provenance:
  context_condition: single_word_transformer
