extends: SMN4Lang_1s.yaml

model:
  use_transformer: false

training:
  output_dir: outputs/SMN4Lang/word_decoding_all_words_mengzi_1s_conv_only_6400updates

provenance:
  context_condition: conv_only
