extends: SMN4Lang_1s.yaml

model:
  context_mode: singleton

training:
  output_dir: outputs/SMN4Lang/word_decoding_all_words_mengzi_1s_single_word_transformer_6400updates

provenance:
  context_condition: single_word_transformer
