extends: ../../../LibriBrain100_1s_single_word_transformer.yaml

experiment:
  task: word_decoding
  dataset: libribrain100
  subject_scope: sub0
  id: historical_singleton_1s
  category: historical_diagnostic
